config/routes.rb
Rails.application.routes.draw do
root "todos#index"
  resources :todos

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :find_todo, only: [:show, :edit, :update, :destroy]
  def index
    @todos = Todo.all
  end

  def show
  end

  def update
    if @todo.update(todo_params)
      redirect_to todos_path
    else
      render 'edit'
    end
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)
    if @todo.save
      redirect_to todos_path
    else
      render 'new'
    end
  end

  def edit
  end

  def destroy
    binding.pry
    @todo.destroy
    redirect_to todos_path
  end

  private

    def todo_params
      params.require(:todo).permit(:title, :description, :complete)
    end

    def find_todo
      @todo = Todo.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todos/_form.html.erb
<%= form_for @todo do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :description %>
  <%= f.text_area :description %>

  <%= f.label :complete %>
  <%= f.check_box :complete %>

  <%= f.submit %>
<% end %>

app/views/todos/edit.html.erb
<h1>Edit Todo</h1>

<%= render "form" %>
</br>

app/views/todos/index.html.erb
<h1>Emmy's Todo List</h1>
<div>
  <ol>
    <% @todos.each do |todo| %>
    <li>
      <%= link_to todo.title, todo_path(todo) %>
      <%= todo.description %>
      <%= todo.complete %>
    </li>
    <% end %>
  </ol>
  <%= link_to "New Todo", new_todo_path %>
  <%= link_to "Show this todo", new_todo_path %>
</div>

app/views/todos/new.html.erb
<h1>New Todo</h1>

<%= render 'form' %>

app/views/todos/show.html.erb
<h1><%= @todo.title %></h1>
<p>Description: <%= @todo.description %></p>
<p>Complete: <%= @todo.complete %></p>

<%= link_to 'All Todos', todos_path %>
<%= link_to 'Update Todo', edit_todo_path(@todo) %>
<%= link_to 'Delete', todo_path(@todo), method: :delete %>